### ISSUE TITLE
Bug in GBDT Iteration

### ISSUE THREAD

**Issue by zhangpengshan** [ShifuML/shifu#360]
017-05-09 18:37:29,837 INFO [main] ml.shifu.guagua.worker.AbstractWorkerCoordinator: Master result size is 970 and read master result run time time 2ms
2017-05-09 18:37:29,837 INFO [main] ml.shifu.guagua.worker.NettyWorkerCoordinator: Master computation is done.
2017-05-09 18:37:29,837 INFO [main] ml.shifu.guagua.worker.MemoryStatsWorkerInterceptor: post iteration:1 with memory info Memory (free/used/total/max) = 1474.06M / 322.44M / 1796.50M / 1796.50M.
2017-05-09 18:37:29,837 INFO [main] ml.shifu.guagua.worker.GcWorkerInterceptor: Application job_1494209372014_24626 container 48 iteration 1 ends with 0ms gc time.
2017-05-09 18:37:29,837 INFO [main] ml.shifu.guagua.worker.WorkerTimer: Application job_1494209372014_24626 container 48 iteration 1 ends with 63592ms execution time.
2017-05-09 18:37:29,837 INFO [main] ml.shifu.guagua.mapreduce.GuaguaMapper: Application progress: 0%.
2017-05-09 18:37:29,837 INFO [main] ml.shifu.guagua.worker.WorkerTimer: Application job_1494209372014_24626 container 48 iteration 2 starts worker computation.
2017-05-09 18:37:29,837 INFO [main] ml.shifu.guagua.worker.GcWorkerInterceptor: Application job_1494209372014_24626 container 48 iteration 2 starts master computation.
2017-05-09 18:37:29,838 INFO [main] ml.shifu.guagua.worker.MemoryStatsWorkerInterceptor: pre iteration:2 with memory info Memory (free/used/total/max) = 1474.06M / 322.44M / 1796.50M / 1796.50M.
2017-05-09 18:37:29,838 INFO [main] ml.shifu.guagua.worker.NettyWorkerCoordinator: Start itertion 2 with container id 48 and app id job_1494209372014_24626.
2017-05-09 18:42:29,838 WARN [main] ml.shifu.guagua.worker.GuaguaWorkerService: Time out for worker computation, null will be returned or mapper will be killed.
2017-05-09 18:42:29,840 ERROR [main] ml.shifu.guagua.mapreduce.GuaguaMapper: Error in guagua main run method.
ml.shifu.guagua.GuaguaRuntimeException: java.lang.NullPointerException
	at ml.shifu.guagua.BasicCoordinator$BasicCoordinatorCommand.execute(BasicCoordinator.java:595)
	at ml.shifu.guagua.worker.NettyWorkerCoordinator.postIteration(NettyWorkerCoordinator.java:416)
	at ml.shifu.guagua.worker.GuaguaWorkerService.iterate(GuaguaWorkerService.java:330)
	at ml.shifu.guagua.worker.GuaguaWorkerService.run(GuaguaWorkerService.java:218)
	at ml.shifu.guagua.mapreduce.GuaguaMapper.run(GuaguaMapper.java:138)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:168)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1724)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:162)
Caused by: java.lang.NullPointerException
	at ml.shifu.guagua.io.BytableSerializer.objectToBytes(BytableSerializer.java:51)
	at ml.shifu.guagua.worker.NettyWorkerCoordinator$6.doExecute(NettyWorkerCoordinator.java:366)
	at ml.shifu.guagua.BasicCoordinator$BasicCoordinatorCommand.execute(BasicCoordinator.java:590)
	... 11 more
2017-05-09 18:42:29,840 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: mapred.task.id is deprecated. Instead, use mapreduce.task.attempt.id
2017-05-09 18:42:29,840 ERROR [main] ml.shifu.guagua.mapreduce.GuaguaMapper: failtask: Killing task: attempt_1494209372014_24626_m_000048_0 
2017-05-09 18:42:29,844 INFO [New I/O worker #1] ml.shifu.guagua.worker.NettyWorkerCoordinator: Master server is down or channel client is disconnected with event [id: 0x181df52b, /10.196.220.29:32942 :> lvshdc2dn1047.lvs.paypal.com/10.196.204.50:44400] DISCONNECTED
2017-05-09 18:42:29,854 INFO [main] org.apache.zookeeper.ZooKeeper: Session: 0x15befff376c0025 closed
2017-05-09 18:42:29,854 INFO [main-EventThread] org.apache.zookeeper.ClientCnxn: EventThread shut down
2017-05-09 18:42:29,854 INFO [main] ml.shifu.guagua.worker.MemoryStatsWorkerInterceptor: post application with memory info Memory (free/used/total/max) = 1552.94M / 246.56M / 1799.50M / 1799.50M.
2017-05-09 18:42:29,854 INFO [main] ml.shifu.guagua.worker.GcWorkerInterceptor: Application job_1494209372014_24626 container 48 ends with 0ms gc time.
2017-05-09 18:42:29,854 INFO [main] ml.shifu.guagua.worker.WorkerTimer: Application job_1494209372014_24626 container 48 ends with 371621ms execution time.
2017-05-09 18:42:29,855 WARN [main] org.apache.hadoop.mapred.YarnChild: Exception running child : ml.shifu.guagua.mapreduce.GuaguaFailTaskRuntimeException: Fail task because of not heathy inside.
	at ml.shifu.guagua.mapreduce.GuaguaMapper.failTask(GuaguaMapper.java:199)
	at ml.shifu.guagua.mapreduce.GuaguaMapper.run(GuaguaMapper.java:170)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:168)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1724)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:162)
Caused by: ml.shifu.guagua.GuaguaRuntimeException: java.lang.NullPointerException
	at ml.shifu.guagua.BasicCoordinator$BasicCoordinatorCommand.execute(BasicCoordinator.java:595)
	at ml.shifu.guagua.worker.NettyWorkerCoordinator.postIteration(NettyWorkerCoordinator.java:416)
	at ml.shifu.guagua.worker.GuaguaWorkerService.iterate(GuaguaWorkerService.java:330)
	at ml.shifu.guagua.worker.GuaguaWorkerService.run(GuaguaWorkerService.java:218)
	at ml.shifu.guagua.mapreduce.GuaguaMapper.run(GuaguaMapper.java:138)
	... 7 more
Caused by: java.lang.NullPointerException
	at ml.shifu.guagua.io.BytableSerializer.objectToBytes(BytableSerializer.java:51)
	at ml.shifu.guagua.worker.NettyWorkerCoordinator$6.doExecute(NettyWorkerCoordinator.java:366)
	at ml.shifu.guagua.BasicCoordinator$BasicCoordinatorCommand.execute(BasicCoordinator.java:590)
	... 11 more

**Comment by zhangpengshan** [comment]
Fail Over make it be ignored while it also should be taken care well

**Comment by zhangpengshan** [comment]
Because of worker run timer for recovering iteration is over configured timout 300s in DTWorker. Then the worker will return a null. Increasing 300 to 500s to avoid that exception.

Why one iteration needs 300s, if over 3000 trees and continuous training, in the 2nd iteration all training records are needed to compute current predictive value for next tree computation. It is time cost.
