### ISSUE TITLE
Issue: Train Failed Because of Zookeeper Crash

### ISSUE THREAD

**Issue by zhangpengshan** [ShifuML/shifu#409]
java.io.IOException: Unable to create snap directory /hadoop/home/pengzhang/shifu/shifu-0.11.0-SNAPSHOT/bin/cam2015-BNN/zookeeper/zkdata/version-2
        at org.apache.zookeeper.server.persistence.FileTxnSnapLog.<init>(FileTxnSnapLog.java:91)
        at org.apache.zookeeper.server.ZooKeeperServerMain.runFromConfig(ZooKeeperServerMain.java:104)
        at org.apache.zookeeper.server.ZooKeeperServerMain.initializeAndRun(ZooKeeperServerMain.java:86)
        at org.apache.zookeeper.server.ZooKeeperServerMain.main(ZooKeeperServerMain.java:52)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:116)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:78)
        at ml.shifu.guagua.coordinator.zk.ZooKeeperUtils$1.run(ZooKeeperUtils.java:334)
        at java.lang.Thread.run(Thread.java:745)
2017-07-21 01:48:52:INFO PurgeTask org.apache.zookeeper.server.DatadirCleanupManager - Purge task completed.

**Comment by zhangpengshan** [comment]
Delete and try again. But in ZooKeeperServerMain such exception will do system.exit(-1), we may need to think another way to fix such issue.
