### ISSUE TITLE
Hadoop2.7.3 with shifu 0.10.5 , pig error

### ISSUE THREAD

**Issue by ji04xiaogang** [ShifuML/shifu#448]
I have run  "build your first model with Shifu tutorial.", with Hadoop 2.7.3  Pseudo-distributed mode on mac.

But when I run the command 'shifu stats ', It run failed,   get error, as follow:

2017-10-22 07:44:13: INFO MapReduceLauncher - Failed!
2017-10-22 07:44:13: INFO SPDTIStatsExecutor - Updating binning info ...
2017-10-22 07:44:13: ERROR StatsModelProcessor - Error:
ShifuException [error=1012: Could not running the pig job or pig job occur internal error, please check your pig log]
	at ml.shifu.shifu.core.processor.stats.MapReducerStatsWorker.doStats(MapReducerStatsWorker.java:121)
	at ml.shifu.shifu.core.processor.StatsModelProcessor.run(StatsModelProcessor.java:214)
	at ml.shifu.shifu.ShifuCLI.calModelStats(ShifuCLI.java:413)
	at ml.shifu.shifu.ShifuCLI.main(ShifuCLI.java:210)
Caused by: java.io.FileNotFoundException: File does not exist: hdfs://localhost:9000/user/leo/ModelSets/tuanData/tmp/UpdatedBinningInfo
	at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1309)
	at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1301)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1301)
	at ml.shifu.shifu.fs.ShifuFileUtils.getDataScanners(ShifuFileUtils.java:258)
	at ml.shifu.shifu.fs.ShifuFileUtils.getDataScanners(ShifuFileUtils.java:231)
	at ml.shifu.shifu.core.processor.stats.MapReducerStatsWorker.updateBinningInfoWithMRJob(MapReducerStatsWorker.java:209)
	at ml.shifu.shifu.core.processor.stats.SPDTIStatsExecutor.runStatsPig(SPDTIStatsExecutor.java:54)
	at ml.shifu.shifu.core.processor.stats.MapReducerStatsWorker.doStats(MapReducerStatsWorker.java:119)
	... 3 more
.

  What is the reason for that ?

**Comment by zhangpengshan** [comment]
@ji04xiaogang thanks for your issue.

In stats step, there are one pig job and one MapReduce job, MapReduce job will read pig output as input which is hdfs://localhost:9000/user/leo/ModelSets/tuanData/tmp/UpdatedBinningInfo. You  needn't to create such folder as it is auto-generated by pig job.

So the root cause is:  pig job is failed, could you please share more detailed logs, and share your ModelConfig.json please. 

Zhang David

**Comment by ji04xiaogang** [comment]
@zhangpengshan  I have resolve  this problem. I illustrated you my analysis, and see if it's right.
   I  have test shifou  on my "linux centos7" with the same hadoop and shifu config, and I found "shifu stats" worked well.   So I'm supposed to be the Mac OS problem.
 When I unpacked the Hadoop installation zip package,  I checked the permissions of the Hadoop folder.
 It shows 
  "drwxr-xr-x@"       hadoop-2.6.5
 And  you can see that in Mac OS has a "@" sign.   At the same time, I set  the Hadoop temp directory in the Hadoop directory,  such as  follow in the core-site.xml
 <property>
       <name>hadoop.tmp.dir</name>
       <value>/Users/wanggang09/hadoop-2.6.5/hadoop-tmp-dir/</value>
    </property>

So  I guess maybe the "@”  permission setting resulted in Shifu unable to write statistics tmp file in hadoop.   So I remove the "@" permissio with "xattr -c hadoop-2.6.5" .
   The "shifu stats" command  It worked well in macOS.
I don't know if my analysis is correct.   

wanggang09

**Comment by zhangpengshan** [comment]
Thanks wanggang09 for your detailed explanation.  That should be correct as it works now:) We didn't test Shifu on non Linux platform, I will create a new issue to make sure our demo works on Mac OS.  

Shifu already shows its power in our production Hadoop platform with stable execution efficiency and pipeline and better model performance while your feedback is very important to improve Shifu. Feel free if you have any issues on further steps. 

Thanks,
Zhang David
