### ISSUE TITLE
Bug in shifu-0.10.5 NN train Model 

### ISSUE THREAD

**Issue by ji04xiaogang** [ShifuML/shifu#454]
I have found a bug in  shifu 0.10.5 version . when use "shifu train" with ModelConfig.json as 
 "train" : {
    "baggingNum" : 1,
    "baggingWithReplacement" : false,
    "baggingSampleRate" : 1.0,
    "validSetRate" : 0.2,
    "numTrainEpochs" : 200,
    "isContinuous" : false,
    "workerThreadCount" : 4,
    "algorithm" : "NN",
    "params" : {
      "Propagation" : "R",
      "LearningRate" : 0.1,
      "NumHiddenNodes" : [ 50 ],
      "NumHiddenLayers" : 1,
      "RegularizedConstant" : 0.0,
      "ActivationFunc" : [ "tanh" ]
    },
    "customPaths" : { }
  },

 I  found it run failed. I show the hadoop log as  follow:

 2017-10-27 16:19:34,294 FATAL [IPC Server handler 28 on 50187] org.apache.hadoop.mapred.TaskAttemptListenerImpl: Task: attempt_1509073250887_0020_m_000000_0 - exited : ml.shifu.guagua.mapreduce.GuaguaFailTaskRuntimeException: Fail task because of not heathy inside.
	at ml.shifu.guagua.mapreduce.GuaguaMapper.failTask(GuaguaMapper.java:199)
	at ml.shifu.guagua.mapreduce.GuaguaMapper.run(GuaguaMapper.java:170)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:784)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1692)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by: ml.shifu.guagua.GuaguaRuntimeException: java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
	at ml.shifu.guagua.master.GuaguaMasterService.start(GuaguaMasterService.java:176)
	at ml.shifu.guagua.mapreduce.GuaguaMapper.setup(GuaguaMapper.java:101)
	at ml.shifu.guagua.mapreduce.GuaguaMapper.run(GuaguaMapper.java:136)
	... 7 more
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
	at ml.shifu.shifu.core.dtrain.nn.NNOutput.initNetwork(NNOutput.java:303)
	at ml.shifu.shifu.core.dtrain.nn.NNOutput.init(NNOutput.java:253)
	at ml.shifu.shifu.core.dtrain.nn.NNOutput.preApplication(NNOutput.java:130)
	at ml.shifu.guagua.master.GuaguaMasterService.start(GuaguaMasterService.java:173)
	... 9 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more

  So I think it maybe something wrong that the runtime cannot found the  "apache-commons-lang3" library jar.

  I  can reproduce this bug in MAC and CentOS, with hadoop 2.6.x and hadoop 2.7.3 .
Please make sure that this bug exists.  

 To help with the analysis, I uploaded log.
[shifu.error.log](https://github.com/ShifuML/shifu/files/1421315/shifu.error.log)

**Comment by zhangpengshan** [comment]
Thanks for your reporting such bug. The root cause is that in our version common-lang3 exists in Hadoop MapReduce libs. Our version is Hortonworks: Hadoop 2.7.3.2.5.3.0-37 and there is one common-lang3: /usr/hdp/2.5.3.0-37/hadoop-mapreduce/commons-lang3-3.4.jar. 

I have fixed such issue in develop branch (by adding common-lang3 to runtime path): https://github.com/ShifuML/shifu/commit/97f41591e3cab62e675002629a9b082d9ec48de1. You can rebuild a shifu tgz file based on develop branch or get one build from [https://github.com/ShifuML/shifu/wiki/shifu-0.11.0-SNAPSHOT-hdp-yarn.tar.gz](https://github.com/ShifuML/shifu/wiki/shifu-0.11.0-SNAPSHOT-hdp-yarn.tar.gz.)

Other work-round you can copy one common-lang3 to your hadoop-mapreduce lib folder(in all nodes).

Thanks,
Zhang David
