### ISSUE TITLE
Error Message: ColumnConfig not Consistent with Header Path or Data Columns

### ISSUE THREAD

**Issue by zhangpengshan** [ShifuML/shifu#491]
If 100 columns in ColumnConfig, 120 in header settings or data columns, there will be exception:

Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 0: Exception while executing (Name: normalized: Filter[bag] - scope-8 Operator Key: scope-8): org.apache.pig.backend.executionengine.ExecException: ERROR 2078: Caught error from UDF: ml.shifu.shifu.udf.NormalizeUDF, Out of bounds access [Index: 8016, Size: 8016]
        at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperator.processInput(PhysicalOperator.java:316)
        at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POFilter.getNextTuple(POFilter.java:91)
        at org.apache.pig.backend.hadoop.executionengine.physicalLayer.PhysicalOperato

**Comment by zhangpengshan** [comment]
Add pre-validation and good suggestion for your
