### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Found interface org.apache.hadoop.mapreduce.JobContext, but class was expected

### ISSUE THREAD

**Issue by wuhaifengdhu** [ShifuML/shifu#504]
N/A	binning_info_partial,data,data_binning_grp,data_cols	GROUP_BY	Message: Unexpected System Error Occured: java.lang.IncompatibleClassChangeError: Found interface org.apache.hadoop.mapreduce.JobContext, but class was expected
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigOutputFormat.setupUdfEnvAndStores(PigOutputFormat.java:235)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigOutputFormat.checkOutputSpecs(PigOutputFormat.java:183)
	at org.apache.hadoop.mapreduce.JobSubmitter.checkSpecs(JobSubmitter.java:266)
	at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:139)
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1290)
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1287)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1866)
	at org.apache.hadoop.mapreduce.Job.submit(Job.java:1287)
	at org.apache.hadoop.mapreduce.lib.jobcontrol.ControlledJob.submit(ControlledJob.java:335)
	at org.apache.hadoop.mapreduce.lib.jobcontrol.JobControl.run(JobControl.java:240)
	at org.apache.pig.backend.hadoop20.PigJobControl.run(PigJobControl.java:121)
	at java.lang.Thread.run(Thread.java:748)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher$1.run(MapReduceLauncher.java:276)

**Comment by wuhaifengdhu** [comment]
I found this error in the latest develop branch, then I changed to use release branch, this problem doesn't exist.

**Comment by zhangpengshan** [comment]
piggybank introduces pig hadoop v1 jar, has been fixed in current develop branch
