### ISSUE TITLE
TrainModelProcessor [main] - Error:/ by zero java.lang.ArithmeticException: / by zero

### ISSUE THREAD

**Issue by zhangpengshan** [ShifuML/shifu#511]
2018-06-05 05:26:48: INFO TrainModelProcessor [main] - Number of train epochs is set to 100.
2018-06-05 05:26:48: ERROR TrainModelProcessor [main] - Error:/ by zero
java.lang.ArithmeticException: / by zero
       at ml.shifu.shifu.core.processor.TrainModelProcessor.computeDynamicCombineSize(TrainModelProcessor.java:1342)
       at ml.shifu.shifu.core.processor.TrainModelProcessor.setHeapSizeAndSplitSize(TrainModelProcessor.java:1277)
       at ml.shifu.shifu.core.processor.TrainModelProcessor.prepareCommonParams(TrainModelProcessor.java:1170)
       at ml.shifu.shifu.core.processor.TrainModelProcessor.runDistributedTrain(TrainModelProcessor.java:387)
       at ml.shifu.shifu.core.processor.TrainModelProcessor.run(TrainModelProcessor.java:209)
       at ml.shifu.shifu.core.processor.VarSelectModelProcessor.distributedSEWrapper(VarSelectModelProcessor.java:639)
       at ml.shifu.shifu.core.processor.VarSelectModelProcessor.run(VarSelectModelProcessor.java:222)
       at ml.shifu.shifu.ShifuCLI.selectModelVar(ShifuCLI.java:455)
       at ml.shifu.shifu.ShifuCLI.main(ShifuCLI.java:260)

**Comment by zhangpengshan** [comment]
Because of stats failed, CC.json is empty, we should add validation if CC.json is empty in followinig steps.
