### ISSUE TITLE
NPE When Big Data Stats in Hadoop 2.2.1 Cluster

### ISSUE THREAD

**Issue by zhangpengshan** [ShifuML/shifu#98]
No matter SPDT or MunroPat mode, there will be exception:

2015-03-16 02:41:17:ERROR main org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.Launcher - java.lang.NullPointerException
        at org.apache.pig.data.BinInterSedes.readSchemaTuple(BinInterSedes.java:168)
        at org.apache.pig.data.BinInterSedes.readDatum(BinInterSedes.java:427)
        at org.apache.pig.impl.io.InterRecordReader.nextKeyValue(InterRecordReader.java:113)
        at org.apache.pig.impl.io.InterStorage.getNext(InterStorage.java:77)
        at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigRecordReader.nextKeyValue(PigRecordReader.java:211)
        at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.nextKeyValue(MapTask.java:533)
        at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
        at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
        at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:144)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:764)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:340)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:167)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1557)

**Comment by zhangpengshan** [comment]
Check the mapper log:

2015-03-30 03:38:52,210 FATAL [main] org.apache.hadoop.mapred.YarnChild: Error running child : java.lang.OutOfMemoryError: Java heap s
pace
        at java.util.Arrays.copyOf(Arrays.java:2271)
        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:113)
        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:140)
        at java.io.DataOutputStream.write(DataOutputStream.java:107)
        at java.io.DataOutputStream.writeUTF(DataOutputStream.java:401)
        at java.io.DataOutputStream.writeUTF(DataOutputStream.java:323)
        at org.apache.pig.data.utils.SedesHelper.writeChararray(SedesHelper.java:66)
        at org.apache.pig.data.BinInterSedes.writeDatum(BinInterSedes.java:580)
        at org.apache.pig.data.BinInterSedes.writeDatum(BinInterSedes.java:462)
        at org.apache.pig.data.utils.SedesHelper.writeGenericTuple(SedesHelper.java:135)
        at org.apache.pig.data.BinInterSedes.writeTuple(BinInterSedes.java:650)
        at org.apache.pig.data.BinInterSedes.writeBag(BinInterSedes.java:641)
        at org.apache.pig.data.BinInterSedes.writeDatum(BinInterSedes.java:474)
        at org.apache.pig.data.BinInterSedes.writeDatum(BinInterSedes.java:462)
        at org.apache.pig.data.utils.SedesHelper.writeGenericTuple(SedesHelper.java:135)
        at org.apache.pig.data.BinInterSedes.writeTuple(BinInterSedes.java:650)
        at org.apache.pig.data.BinInterSedes.writeDatum(BinInterSedes.java:470)
        at org.apache.pig.data.BinSedesTuple.write(BinSedesTuple.java:40)
        at org.apache.pig.impl.io.PigNullableWritable.write(PigNullableWritable.java:126)
        at org.apache.hadoop.io.serializer.WritableSerialization$WritableSerializer.serialize(WritableSerialization.java:98)
        at org.apache.hadoop.io.serializer.WritableSerialization$WritableSerializer.serialize(WritableSerialization.java:82)
        at org.apache.hadoop.mapred.IFile$Writer.append(IFile.java:211)
        at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.spillSingleRecord(MapTask.java:1676)
        at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.collect(MapTask.java:1160)
        at org.apache.hadoop.mapred.MapTask$NewOutputCollector.write(MapTask.java:692)
        at org.apache.hadoop.mapreduce.task.TaskInputOutputContextImpl.write(TaskInputOutputContextImpl.java:89)
        at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.write(WrappedMapper.java:112)

**Comment by zhangpengshan** [comment]
Add SPDTI mode to stats step. Already done in develop 0.2.5. Doc will be added.
